sources:
  - name: PetStore
    handler:
      openapi:
        # OpenAPI の取得元（ローカルでもURLでもOK）
        source: ./openapi.json
        # 実呼び出しのベースURL（v0ドキュメントで正式サポート）
        endpoint: https://petstore3.swagger.io/api/v3
  - name: Space
    handler:
      graphql:
        endpoint: https://countries.trevorblades.com/
